COMP = g++
ALG = -lallegro -lallegro_image -lallegro_primitives -lallegro_font -lallegro_ttf -lallegro_audio -lallegro_acodec

TARGET = FlowFree
all: $(TARGET)

$(TARGET) : *.cpp
				$(COMP) -o $(TARGET) *.cpp $(ALG) -g